"""add phone number column to users

Revision ID: 863d7977c24f
Revises: e16112d930fe
Create Date: 2023-03-16 13:41:52.561042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863d7977c24f'
down_revision = 'e16112d930fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
